sudo: required
language: node_js
node_js:
  - "lts/*"
services:
  - docker
if: type = pull_request
script:
  - npm run lint
  - npm run docker:test
notifications:
  email: false
env:
  matrix:
    secure: FEIvORveRz4paPRQ1dKaPMFOL6TfftfIT0RuKgwA/mGG/QDq5HOTQNOwXlxd+quqj8o6JM/VfZMtOLEyJc436APHT4EU1yv5tfvyOIaywf7/XWEzOnUwBXbaDfbpnLpcLFL9HeDHEsvXcteyzNT18KTTAf4UnijlTYCg7LSSLCBnVK6XlSG942/Mr4OIP8MRRYYxgxnabducGHa9TUHmc1BT43vSPESv8BybKk8K5dM+tiD6YqCdatPA4wbjVKdvNwBq+Ps0652/JyCjHd5feRKGrcW17rBr/er8EwpZBPxRIttKDq5f5yUD+r9lfBD5EEjMsogvoteoQvFS1vod5CIZXILtI+g7HmtpT6EEglRnsnhaCK5Czkb9tWf0TyawrYfLSep4zxmDxJEFYTZ7cZvaDWf8KR6W0N7lPb16yqsnHaPAduQ0ejLa14SkhMembLqPKM5bOAbKhzCGcWvSjShNxnmKKsJnDliI0s9ozAUjGTFI9VuIibKaLzJZUR/V0e2IPxPKcK74KfAFh145WWmqK8kw9ju/Q5Gxbo5m1KXo1SmMH5BV3j6GI9Gr274ZrxnahZauUMFFuvNjQMtGRscSf4+9xpnTIq+r1Rt8qlxgWG/VwgZkLN8h1cTGrweh32VcuivlWjTWjzv375i55fp2rciKhqjOgzGbMk7e7BQ=
