name: Integration Tests

on: [push]

jobs:
  test-app: 
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'

    - name: Install Process Manager for Node.js
      run: |
        set -x
        npm install -g pm2

    - name: Install dependencies
      run: |
        set -x
        npm install

    - name: Start JSON Server
      run: pm2 start ./node_modules/.bin/json-server -- ./db.json

    - name: Run tests
      run: npm test

    - name: Stop JSON Server
      run: pm2 stop all

    - name: Run build
      run: |
        cd /home/runner/work/testing-js-course-2021/4-Integration-Testing/good-architecture
        npm add @babel/core @babel/core @babel/preset-env
        npm run build

    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: dist-without-markdown
        path: |
          cd /home/runner/work/testing-js-course-2021/4-Integration-Testing/good-architecture
          dist/*
