name: Tests

on: [push]

jobs:
  test-job: ubuntu-latest
  steps:
  - name: Checkout
    uses: actions/checkout@v2

  - name: Setup Node.js
    uses: actions/setup-node@v1
    with:
      node-version: '14.16'
  
  - name: Install dependencies
    run: |
      set -x
      npm install

  - name: Run tests
    run: npm test